# Generated by Django 4.2.7 on 2025-06-28 22:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='technology_used',
        ),
    ]
