# Generated by Django 4.2.7 on 2025-06-28 23:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_auto_20250629_0050'),
    ]

    operations = [
        migrations.AddField(
            model_name='projecttagassignment',
            name='assigned_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
